import Navigation from "../components/navigation"
import AboutUsLayout from "./about-us/layout"

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation  />
        {children}
      </body>
    </html>
  )
}